/*DDK*************************************************************************/
/*                                                                           */
/* COPYRIGHT    Copyright (C) 1991, 2003 IBM Corporation                     */
/*                                                                           */
/*    The following IBM OS/2 source code is provided to you solely for       */
/*    the purpose of assisting you in your development of OS/2 device        */
/*    drivers. You may use this code in accordance with the IBM License      */
/*    Agreement provided in the IBM Developer Connection Device Driver       */
/*    Source Kit for OS/2. This Copyright statement may not be removed.      */
/*                                                                           */
/*****************************************************************************/

/*******************************************/
/* inc\fontres.h                           */
/*                                         */
/* This file contains a list of all the    */
/* fonts we have in our resources.  The    */
/* index of each font name in the list     */
/* corresponds to its resource number.     */
/*                                         */
/* This file was generated by the font     */
/* preparation utility, fontprep.          */
/*******************************************/

#define     FONTGRP   300

PCHAR FontResourceName[] =
   { "-",                            /* There is no resource zero */
     "AvantGarde-Book",
     "AvantGarde-BookOblique",
     "AvantGarde-Demi",
     "AvantGarde-DemiOblique",
     "Bookman-Demi",
     "Bookman-DemiItalic",
     "Bookman-Light",
     "Bookman-LightItalic",
     "Courier-Bold",
     "Courier-BoldOblique",
     "Courier",
     "Courier-Oblique",
     "Garamond-Bold",
     "Garamond-BoldItalic",
     "Garamond-Light",
     "Garamond-LightItalic",
     "AGaramond-Bold",
     "AGaramond-BoldItalic",
     "AGaramond-Italic",
     "AGaramond-Regular",
     "AGaramond-Semibold",
     "AGaramond-SemiboldItalic",
     "Helvetica-Bold",
     "Helvetica-BoldOblique",
     "Helvetica",
     "Helvetica-Oblique",
     "Helvetica-Black",
     "Helvetica-BlackOblique",
     "Helvetica-Condensed",
     "Helvetica-Condensed-Bold",
     "Helvetica-Condensed-BoldObl",
     "Helvetica-Condensed-Oblique",
     "Helvetica-Light",
     "Helvetica-LightOblique",
     "Helvetica-Narrow",
     "Helvetica-Narrow-Bold",
     "Helvetica-Narrow-BoldOblique",
     "Helvetica-Narrow-Oblique",
     "Korinna-Bold",
     "Korinna-KursivBold",
     "Korinna-KursivRegular",
     "Korinna-Regular",
     "LubalinGraph-Book",
     "LubalinGraph-BookOblique",
     "LubalinGraph-Demi",
     "LubalinGraph-DemiOblique",
     "NewCenturySchlbk-Bold",
     "NewCenturySchlbk-BoldItalic",
     "NewCenturySchlbk-Italic",
     "NewCenturySchlbk-Roman",
     "Palatino-Bold",
     "Palatino-BoldItalic",
     "Palatino-Italic",
     "Palatino-Roman",
     "Souvenir-Demi",
     "Souvenir-DemiItalic",
     "Souvenir-Light",
     "Souvenir-LightItalic",
     "Symbol",
     "Times-Bold",
     "Times-BoldItalic",
     "Times-Italic",
     "Times-Roman",
     "Varitimes#Bold",
     "Varitimes#BoldItalic",
     "Varitimes#Italic",
     "Varitimes#Roman",
     "ZapfChancery-MediumItalic",
     "ZapfDingbats",
       0
  } ;

PCHAR FontFullName[] =
   { "-",                            /* There is no resource zero */
     "ITC Avant Garde Gothic Book",
     "ITC Avant Garde Gothic Book Obl",
     "ITC Avant Garde Gothic Demi",
     "ITC Avant Garde Gothic Demi Obl",
     "ITC Bookman Demi",
     "ITC Bookman Demi Italic",
     "ITC Bookman Light",
     "ITC Bookman Light Italic",
     "Courier Bold",
     "Courier Bold Oblique",
     "Courier",
     "Courier Oblique",
     "ITC Garamond Bold",
     "ITC Garamond Bold Italic",
     "ITC Garamond Light",
     "ITC Garamond Light Italic",
     "Adobe Garamond Bold",
     "Adobe Garamond Bold Italic",
     "Adobe Garamond Italic",
     "Adobe Garamond Regular",
     "Adobe Garamond Semibold",
     "Adobe Garamond Semibold Italic",
     "Helvetica Bold",
     "Helvetica Bold Oblique",
     "Helvetica",
     "Helvetica Oblique",
     "Helvetica Black",
     "Helvetica Black Oblique",
     "Helvetica Condensed Medium",
     "Helvetica Condensed Bold",
     "Helvetica Condensed Bold Obliqu",
     "Helvetica Condensed Oblique",
     "Helvetica Light",
     "Helvetica Light Oblique",
     "Helvetica Narrow",
     "Helvetica Narrow Bold",
     "Helvetica Narrow Bold Oblique",
     "Helvetica Narrow Oblique",
     "ITC Korinna Bold",
     "ITC Korinna Kursiv Bold",
     "ITC Korinna Kursiv Regular",
     "ITC Korinna Regular",
     "ITC Lubalin Graph Book",
     "ITC Lubalin Graph Book Oblique",
     "ITC Lubalin Graph Demi",
     "ITC LubalinGraph Demi Oblique",
     "New Century Schoolbook Bold",
     "New Century Schoolbook Bold Ita",
     "New Century Schoolbook Italic",
     "New Century Schoolbook Roman",
     "Palatino Bold",
     "Palatino Bold Italic",
     "Palatino Italic",
     "Palatino Roman",
     "ITC Souvenir Demi",
     "ITC Souvenir Demi Italic",
     "ITC Souvenir Light",
     "ITC Souvenir Light Italic",
     "Symbol",
     "Times Bold",
     "Times Bold Italic",
     "Times Italic",
     "Times Roman",
     "Times Bold Varitimes",
     "Times Bold Italic Varitimes",
     "Times Italic Varitimes",
     "Times Roman Varitimes",
     "ITC Zapf Chancery Medium Italic",
     "ITC Zapf Dingbats",
       0
  } ;

